import { activityID } from "./useWorkspaceActivity";
import { resourceKey } from "./workspaceModel";
import { contextFor, EmptyWidget, ResourceButton, ResourceMark, StateBadge, WidgetSection, widgetButton, type SystemWidgetProps } from "./WorkspaceWidgetUI";

export function InspectorWidget(props: SystemWidgetProps) {
  const { context, actions } = contextFor(props);
  const { resources, edges, states, activity, highlighted } = props.system;
  const resource = context.selected && resources.get(resourceKey(context.selected));
  const relationships = resource?.ref.type === "agent" ? edges.get(Number(resource.ref.id)) || [] : [...edges].filter(([, keys]) => resource && keys.includes(resourceKey(resource.ref))).map(([id]) => `agent:${id}`);
  const state = resource?.ref.type === "agent" ? states.get(Number(resource.ref.id)) : undefined;
  const latest = resource && [...activity.values()].reverse().find(row => resource.ref.type === "agent" ? row.item.raw.instance_id === Number(resource.ref.id) : row.resource && resourceKey(row.resource.ref) === resourceKey(resource.ref));
  const change = resource && highlighted.get(resourceKey(resource.ref));
  const management = resource?.ref.type === "app" ? "Manage apps" : resource?.ref.type === "integration" ? "Manage integrations" : resource?.ref.type === "skill" ? "Manage skills" : "Manage agent";
  return <WidgetSection title="Inspector" description="Details, connections, and actions." action={context.selected && <button className={widgetButton} onClick={() => actions.dispatch({ type: "clear_selection" })}>Clear</button>}>
    {!resource ? <EmptyWidget title={context.selected ? "This resource is unavailable" : "Select something to explore"} detail={context.selected ? "It may have been removed or be outside the current scope. Refresh the system to check." : "Choose an agent, app, or integration on the map to see its role and connections."}>{context.selected && <button className={widgetButton} onClick={props.refresh}>Refresh</button>}</EmptyWidget> : <div className="min-h-0 max-h-[640px] flex-1 space-y-4 overflow-auto p-4">
      <div className="flex items-center gap-3"><ResourceMark resource={resource} /><div className="min-w-0 flex-1"><h3 className="break-words text-sm font-semibold">{resource.name}</h3><p className="text-[11px] capitalize text-text-dim">{resource.ref.type} · {props.projectNames.get(resource.ref.projectId || "") || "Global"}</p></div></div>
      <div className="flex flex-wrap items-center gap-2"><StateBadge label={state?.label || resource.status} live={state?.live} attention={state?.attention || ["error", "failed"].includes(resource.status)} />{change && <span className="text-xs text-accent">{change.detail}</span>}</div>
      {state?.detail && <p className="text-xs leading-relaxed text-text-muted">{state.detail}</p>}
      <div className="flex flex-wrap gap-2">{resource.href && resource.href !== resource.configureHref && <button className={widgetButton} onClick={() => actions.dispatch({ type: "open", resource: resource.ref })}>Open {resource.ref.type}</button>}<button className={widgetButton} onClick={() => actions.dispatch({ type: "configure", resource: resource.ref })}>{management}</button><button className={widgetButton} onClick={() => actions.dispatch({ type: "ask_helper", prompt: `Help me understand and improve ${resource.ref.type} “${resource.name}” (ID ${resource.ref.id})${resource.ref.projectId ? ` in project ${resource.ref.projectId}` : ""}.` })}>Ask Helper</button></div>
      {resource.description && (resource.ref.type === "agent" ? <details><summary className="cursor-pointer text-xs font-semibold">Agent instructions</summary><p className="mt-2 max-h-48 overflow-auto whitespace-pre-wrap break-words text-xs leading-relaxed text-text-muted">{resource.description}</p></details> : <p className="whitespace-pre-wrap break-words text-xs leading-relaxed text-text-muted">{resource.description}</p>)}
      <dl className="space-y-2">{resource.fields.filter(([, value]) => !!value).map(([label, value]) => <div key={label} className="grid grid-cols-[80px_minmax(0,1fr)] gap-3 text-xs"><dt className="text-text-dim">{label}</dt><dd className="break-words">{value}</dd></div>)}</dl>
      {latest && <button type="button" className="w-full rounded-lg border border-border p-3 text-left hover:border-accent/50" onClick={() => actions.dispatch({ type: "select_activity", id: activityID(latest.item), resource: { type: "agent", id: latest.item.raw.instance_id, label: props.agents.find(agent => agent.id === latest.item.raw.instance_id)?.name, projectId: resource.ref.projectId } })}><span className="block text-[10px] text-text-dim">Latest recorded activity</span><span className="mt-1 block text-xs font-semibold">{latest.title} →</span><span className="mt-1 line-clamp-2 text-xs text-text-muted">{latest.summary}</span></button>}
      <section><h4 className="mb-2 text-xs font-semibold">{resource.ref.type === "agent" ? "Attached capabilities" : "Used by agents"} · {relationships.length}</h4><p className="mb-3 text-[11px] text-text-dim">{resource.ref.type === "agent" ? "These connections give the agent tools or instructions." : "Select an agent to inspect its configuration."}</p><div className="space-y-2">{relationships.map(key => resources.get(key)).filter(item => !!item).map(item => <ResourceButton key={resourceKey(item.ref)} resource={item} selected={context.selected} onSelect={actions.select} />)}</div>{relationships.length === 0 && <p className="text-xs text-text-muted">{resource.ref.type === "agent" && !props.attachments[Number(resource.ref.id)] ? "Loading attachments…" : "No confirmed connections in this scope."}</p>}</section>
    </div>}
  </WidgetSection>;
}
