// Code-gen the vendor entry files from React's actual runtime
// surface. The previous approach — hand-enumerating React's
// exports — kept missing things (jsxDEV, createPortal,
// __CLIENT_INTERNALS_DO_NOT_USE_OR_WARN_USERS_THEY_CANNOT_UPGRADE,
// __COMPILER_RUNTIME) and the dashboard kept breaking with
// "does not provide an export named …" or "Cannot read properties
// of undefined (reading 'S')" — react-dom looks up the
// dispatcher via the internals object, so missing it is fatal.
//
// Every name React's package returns at runtime gets a real ESM
// re-export here. New React minor adds internals? They'll show up
// automatically next build. New deprecation? The old name keeps
// working until React removes it.
//
// Run by build.ts before Bun.build of the vendor bundles.

import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const HERE = dirname(fileURLToPath(import.meta.url));
const VENDOR = join(HERE, "..", "vendor");

interface VendorPlan {
  module: string;       // npm module name (e.g. "react")
  importPath?: string;  // override: what the entry should `import` from
                        // (Bun keeps subpath specifiers like
                        // "react/jsx-runtime" as bare imports even
                        // outside the external list — work around by
                        // importing the literal file path)
  outFile: string;      // entry filename (vendor/<x>.entry.ts)
  notes: string;        // top-of-file comment
}

const PLANS: VendorPlan[] = [
  {
    module: "react",
    outFile: "react.entry.ts",
    notes: `// Re-export every name React's package returns. Auto-generated by
// scripts/gen-vendor-entries.ts. Hand-edits will be overwritten —
// edit the generator instead if you need to change the surface.`,
  },
  {
    module: "react/jsx-runtime",
    // Bun's `external: ["react"]` is package-aware — it keeps every
    // "react/*" subpath bare too. So we can't import "react/jsx-runtime"
    // (self-import via importmap) OR "react/jsx-runtime.js" (still a
    // bare specifier the browser can't resolve). Use a relative path
    // into node_modules so Bun treats it as a local file and inlines it.
    importPath: "../node_modules/react/jsx-runtime.js",
    outFile: "react-jsx-runtime.entry.ts",
    notes: `// Re-export every name react/jsx-runtime exposes. Auto-generated.`,
  },
  {
    module: "react-dom",
    outFile: "react-dom.entry.ts",
    notes: `// Re-export every name react-dom exposes (createPortal, flushSync,
// preload, etc. — distinct from react-dom/client's createRoot).
// Auto-generated.`,
  },
  {
    module: "react-dom/client",
    outFile: "react-dom-client.entry.ts",
    notes: `// Re-export every name react-dom/client exposes (createRoot,
// hydrateRoot). Auto-generated.`,
  },
];

function isValidIdent(name: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name);
}

async function main() {
  for (const plan of PLANS) {
    // require() runs in a separate node process so React's
    // production-mode init isn't poisoned by Bun's module loading.
    const procResult = await Bun.spawn(
      ["node", "-e", `console.log(JSON.stringify(Object.keys(require('${plan.module}')).filter(k => k !== 'default')))`],
      { stdout: "pipe", stderr: "pipe" },
    );
    const exitCode = await procResult.exited;
    if (exitCode !== 0) {
      const err = await new Response(procResult.stderr).text();
      console.error(`✗ couldn't enumerate "${plan.module}":`, err);
      process.exit(1);
    }
    const keysText = await new Response(procResult.stdout).text();
    const keys: string[] = JSON.parse(keysText.trim());
    const valid = keys.filter(isValidIdent);
    if (valid.length === 0) {
      console.error(`✗ "${plan.module}" has no enumerable named exports — CJS interop is broken`);
      process.exit(1);
    }

    // Generate the entry file. Two halves:
    //   1. import the module as a namespace
    //   2. for each key, `export const X = (Mod as any).X`
    // Plus a default re-export so callers using `import M from
    // 'react'` still work.
    const lines: string[] = [];
    lines.push(plan.notes);
    lines.push("");
    lines.push(`// @ts-ignore — CJS module, both default + named exposed at runtime.`);
    lines.push(`import * as Mod from "${plan.importPath ?? plan.module}";`);
    lines.push(`export default (Mod as any).default ?? (Mod as any);`);
    for (const k of valid) {
      lines.push(`export const ${k} = (Mod as any).${k};`);
    }
    lines.push("");
    const out = join(VENDOR, plan.outFile);
    writeFileSync(out, lines.join("\n"));
    console.log(`✓ generated ${plan.outFile} from "${plan.module}" (${valid.length} names)`);
  }
}

await main();
